#!/data/data/com.termux/files/usr/bin/bash

# config
max_usage=90
bar_width=50
# colors
white="\e[39m"
green="\e[1;32m"
red="\e[1;31m"
yellow="\e[1;33m"
cyan="\e[1;36m"
dim="\e[2m"
undim="\e[0m"
NC='\033[0m'
BOLD='\033[1m'

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

uptime | grep -Po "average: \K.+"| awk -F", " '{ print $1,$2,$3 }' > $tmp/load
IFS=" " read LOAD1 LOAD5 LOAD15 <<<$(cat $tmp/load)
IFS=" " read USED AVAIL TOTAL <<<$(free -htm | grep "Mem" | awk {'print $3,$7,$2'})

if [[ -d /system/app/ && -d /system/priv-app ]]; then
    DISTRO="Android $(getprop ro.build.version.release)"
    MODEL="$(getprop ro.product.brand) $(getprop ro.product.model)"
fi

echo -e "
${White}${BOLD}System Info:
$cyan  Distro    : $white$DISTRO
$cyan  Host      : $white$MODEL
$cyan  Uptime    : $white$(uptime -p)
$cyan  Load      : $green$LOAD1$white (1m), $green$LOAD5$white (5m), $green$LOAD15$white (15m)
$cyan  Memory    : $green$USED$white used, $green$AVAIL$white avail, $green$TOTAL$white total$W"
