#!/data/data/com.termux/files/usr/bin/env bash

[ -d "$PREFIX/etc/motd" ] && MOTD="$PREFIX/etc/motd"

for i in $(find $MOTD -maxdepth 1 -regex '.+/[0-9\-].+' -not -regex ".+\.no" | sort)
do
    bash $i
done

python3 quote
