#!/data/data/com.termux/files/usr/bin/env bash

[ -d "$PREFIX/etc/motd" ] && MOTD="$PREFIX/etc/motd"

for i in $(find $MOTD -maxdepth 1 -regex '.+/[0-9\-].+' -not -regex ".+\.no" | sort)
do
    bash $i
done

if [[ -x $PREFIX/bin/python ]]; then
    python3 quote
fi

if [[ -x $PREFIX/bin/locate ]]; then
    updatedb --database-root /storage/emulated/0/ --output ~/.local/mlocate/storage.db
    updatedb
fi
